# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: d1c164db4c2661faa851a693b571106c687fc9e9948efeb7178cba3e49f191a3caaaaa12779e3b1b3a69ff4d500be3056aea3ca471564db8840a3d17424baa14

test:
  domain_name: example.com 
  secret_key_base: 903f01935f1bf112aef27ff3255c283010c64131231884de52523b3bb0fd7ebedac37c7e44a00d7c07cd839b79b42dc6791c2f304d659305112a3c620464c104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
