# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92b9b999b6fc687061bc856bf05aa435e9d3dd2347c2fdc7878beca2b62a062afe1037629291ebcce741218c9d798738fbc4b7c9c9ed92353aac9f4eef4d92a7

test:
  secret_key_base: f58a903c92a2f4eeed34b052c7a10ab28f123ed17a183be673ccb568ffa7a92ca890602d61f8df2afe707c449ca3aacf62920a81bff5c8cb2b1133a289e002c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
